package com.mycompany.projetjava;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.mycompany.projetjava.models.Activity;
import com.mycompany.projetjava.models.ActivityType;
import com.mycompany.projetjava.services.ActivityService;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ActivityDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActivityDialog.class.getName());
    
    private DateTimePicker dateTimePicker;
    Activity activity_edit;
    
    /**
     * Creates new form AddActivityDialog
     */
    public ActivityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        titleLabel.setText("Ajouter une activité");
            
        initDateTimePicker();
        fillTypeSelect();
        fillTitleLabel();
        
    }
    
    public ActivityDialog(java.awt.Frame parent, boolean modal, Activity activity){
        super(parent, modal);
        initComponents();
        
        this.activity_edit = activity;
        
        titleLabel.setText("Modifier une activité");
        initDateTimePicker();
        fillTitleLabel();
        fillDescription();
        fillTypeSelect();
        fillDuration();
    }
    
    private void fillDuration(){
        if(activity_edit != null){
            int duration = activity_edit.getDuration();
            int hours = duration / 3600;
            int minutes = (duration % 3600) / 60;
            int seconds = duration % 60;
            
            hoursInput.setValue(hours);
            minutesInput.setValue(minutes);
            secondsInput.setValue(seconds);
        }
    }
    
    private void fillDescription(){
        if(activity_edit != null){
            descriptionInput.setText(activity_edit.getDescription());
        }
    }
    
    private void fillTitleLabel(){
        if(activity_edit == null){
            LocalDateTime currentDateTime = dateTimePicker.getDateTimePermissive();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            String formattedDateTime = currentDateTime.format(formatter);
            titleInput.setText("Activity - " + formattedDateTime);
        }
        else {
            titleInput.setText(activity_edit.getTitle());
        }
    }
    
    private void initDateTimePicker(){
        this.dateTimePicker = new DateTimePicker();
        if(activity_edit == null){
            dateTimePicker.datePicker.setDateToToday(); 
            dateTimePicker.timePicker.setTimeToNow();
        } else{
            dateTimePicker.setDateTimeStrict(activity_edit.getDateTime());
        }
        
        panelDateTime.add(dateTimePicker);
        panelDateTime.revalidate();
        panelDateTime.repaint();
    }
    
    private void fillTypeSelect(){
        try{
            ActivityService s = new ActivityService();
            ArrayList<ActivityType> types = s.getAllActivityTypes();
            for(ActivityType type : types){
                typeSelect.addItem(type);
                if(activity_edit != null && activity_edit.getType().getName().equalsIgnoreCase(type.getName())){
                    typeSelect.setSelectedItem(type);
                }
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, 
                "Error during activity types loading!",
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        titleInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionInput = new javax.swing.JTextArea();
        typeSelect = new javax.swing.JComboBox<>();
        panelDateTime = new javax.swing.JPanel();
        hoursInput = new javax.swing.JSpinner();
        minutesInput = new javax.swing.JSpinner();
        secondsInput = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Titre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Description (facultatif)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date et heure");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Durée");

        titleInput.addActionListener(this::titleInputActionPerformed);

        descriptionInput.setColumns(20);
        descriptionInput.setRows(5);
        jScrollPane1.setViewportView(descriptionInput);

        panelDateTime.setLayout(new java.awt.BorderLayout());

        hoursInput.setModel(new javax.swing.SpinnerNumberModel(1, 0, 24, 1));

        minutesInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        secondsInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel5.setText("Hours");

        jLabel7.setText("Minutes");

        jLabel8.setText("Seconds");

        confirmButton.setText("Confirmer");
        confirmButton.addActionListener(this::confirmButtonActionPerformed);

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Add an activity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(titleInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(panelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(typeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(hoursInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(minutesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(secondsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(confirmButton)
                                        .addGap(100, 100, 100)
                                        .addComponent(cancelButton)
                                        .addGap(121, 121, 121))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(titleLabel)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(titleLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(panelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hoursInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(confirmButton)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleInputActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        String title = titleInput.getText();
        String description = descriptionInput.getText();
        ActivityType type = (ActivityType) typeSelect.getSelectedItem();
        LocalDateTime datetime = dateTimePicker.getDateTimePermissive();
        int hours = (int) hoursInput.getValue();
        int minutes = (int) minutesInput.getValue();
        int seconds = (int) secondsInput.getValue();
        int duration = hours * 3600 + minutes * 60 + seconds;

        if(activity_edit != null){
            activity_edit.setTitle(title);
            activity_edit.setDescription(description);
            activity_edit.setType(type);
            activity_edit.setDateTime(datetime);
            activity_edit.setDuration(duration);
        }
        
        
        Activity activity = new Activity(title, description, type, datetime, duration, UserSession.getInstance().getUser());
        ActivityService as = new ActivityService();
        
        try{
            if(activity_edit == null){
                as.add(activity);
            } else{
                as.update(activity_edit);
            }
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, 
                "Une erreur est survenu en essayant de créer la nouvelle activité : " + title,
                "Erreur : Base de données",
                JOptionPane.ERROR_MESSAGE
            );
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Erreur : Gestion des activités",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ActivityDialog dialog = new ActivityDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextArea descriptionInput;
    private javax.swing.JSpinner hoursInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner minutesInput;
    private javax.swing.JPanel panelDateTime;
    private javax.swing.JSpinner secondsInput;
    private javax.swing.JTextField titleInput;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<ActivityType> typeSelect;
    // End of variables declaration//GEN-END:variables
}
