/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projetjava;

import com.mycompany.projetjava.models.Activity;
import com.mycompany.projetjava.services.ActivityService;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathan
 */
public class ActivityCard extends javax.swing.JPanel {

    /**
     * Creates new form ActivityCard
     */
    public ActivityCard() {
        initComponents();

        java.awt.Color fondCarte = new java.awt.Color(60, 63, 65);
        java.awt.Color bleuAccent = new java.awt.Color(0, 120, 215);
        java.awt.Color textePrincipal = java.awt.Color.WHITE;
        java.awt.Color texteSecondaire = new java.awt.Color(180, 180, 180);

        setBackground(fondCarte);
        javax.swing.border.Border contour = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 85, 85), 1, true); 
        javax.swing.border.Border padding = javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20);
        setBorder(javax.swing.BorderFactory.createCompoundBorder(contour, padding));

        nameLabel.setForeground(textePrincipal);
        dateLabel.setForeground(textePrincipal);

        titleLabel.setForeground(bleuAccent);

        typeDurationLabel.setForeground(texteSecondaire);
        descriptionLabel.setForeground(textePrincipal);

        int largeur = 600;
        int hauteur = this.getPreferredSize().height;
        this.setPreferredSize(new java.awt.Dimension(largeur, hauteur));
        this.setMaximumSize(new java.awt.Dimension(largeur, hauteur));
        this.setMinimumSize(new java.awt.Dimension(largeur, hauteur));
    }

    private String type = "";
    private String duration = "";
    private Activity activity;
    
    public void setActivity(Activity activity) {
        this.activity = activity;
        setTitle(activity.getTitle());
        setDescription(activity.getDescription());
        setDate(activity.getDateTime());
        setDuration(activity.getDuration());
        setType(activity.getType().toString());
    }
    
    public void setTitle(String title){
        titleLabel.setText(title);
    }
    
    public void setDescription(String description){
        descriptionLabel.setText("<html>Description : " + description + "</html>");
    }
    
    public void setType(String type){
        this.type = type;
        updateTypeDurationLabel();
    }
    
    public void setDuration(int duration) {
        int hours = duration / 3600;
        int minutes = (duration % 3600) / 60;
        int seconds = duration % 60;

        if (hours > 0) {
            this.duration = hours + "h " + minutes + "m " + seconds + "s";
        } else {
            this.duration = minutes + "m " + seconds + "s";
        }
        updateTypeDurationLabel();
    }
    
    public void updateTypeDurationLabel(){
        typeDurationLabel.setText(type + " - " + duration);
    }
    
    public void setDate(LocalDateTime date){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE d MMMM yyyy 'à' HH'h'mm", Locale.FRENCH);
        String formatedDate = date.format(formatter);
        dateLabel.setText(formatedDate);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durationLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        typeDurationLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        durationLabel.setText("Durée : ");

        descriptionLabel.setText("Description : ");
        descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        typeDurationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeDurationLabel.setText("Type  - Durée");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("ActivityName");

        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date");
        dateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        nameLabel.setText("FirstName LastName");

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_icon.png"))); // NOI18N
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(dateLabel))
                .addGap(18, 18, 18)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(typeDurationLabel)
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Êtes-vous sûr de vouloir supprimer l'activité : " + this.activity.getTitle() + " ?");
        if(choice == JOptionPane.YES_OPTION){
            ActivityService as = new ActivityService();
            try{
                as.delete(activity);
                
                java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
                if (parentWindow instanceof HomePage home) {
                    home.refreshActivities();
                }
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this, 
                    "Error while deleting the activity!",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel typeDurationLabel;
    // End of variables declaration//GEN-END:variables
}
