package com.mycompany.projetjava;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.mycompany.projetjava.models.Activity;
import com.mycompany.projetjava.models.ActivityType;
import com.mycompany.projetjava.services.ActivityService;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AddActivityDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddActivityDialog.class.getName());
    
    private DateTimePicker dateTimePicker;
    
    /**
     * Creates new form AddActivityDialog
     */
    public AddActivityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        initDateTimePicker();
        fillTypeSelect();
        fillTitleLabel();
    }
    
    private void fillTitleLabel(){
        LocalDateTime currentDateTime = dateTimePicker.getDateTimePermissive();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        String formattedDateTime = currentDateTime.format(formatter);
        addActivityTitleInput.setText("Activity - " + formattedDateTime);
    }
    
    private void initDateTimePicker(){
        this.dateTimePicker = new DateTimePicker();
        dateTimePicker.datePicker.setDateToToday(); 
        dateTimePicker.timePicker.setTimeToNow();
        panelDateTime.add(dateTimePicker);
        panelDateTime.revalidate();
        panelDateTime.repaint();
    }
    
    private void fillTypeSelect(){
        try{
            ActivityService s = new ActivityService();
            ArrayList<ActivityType> types = s.getAllActivityTypes();
            for(ActivityType type : types){
                addActivityTypeSelect.addItem(type);
            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, 
                "Error during activity types loading!",
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addActivityTitleInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addActivityDescriptionInput = new javax.swing.JTextArea();
        addActivityTypeSelect = new javax.swing.JComboBox<>();
        panelDateTime = new javax.swing.JPanel();
        addActivityHoursInput = new javax.swing.JSpinner();
        addActivityMinutesInput = new javax.swing.JSpinner();
        addActivitySecondsInput = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addActivityConfirmButton = new javax.swing.JButton();
        addActivityCancelButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Title");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Description (optional)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Date and time");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Duration");

        addActivityTitleInput.addActionListener(this::addActivityTitleInputActionPerformed);

        addActivityDescriptionInput.setColumns(20);
        addActivityDescriptionInput.setRows(5);
        jScrollPane1.setViewportView(addActivityDescriptionInput);

        panelDateTime.setLayout(new java.awt.BorderLayout());

        addActivityHoursInput.setModel(new javax.swing.SpinnerNumberModel(1, 0, 24, 1));

        addActivityMinutesInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        addActivitySecondsInput.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel5.setText("Hours");

        jLabel7.setText("Minutes");

        jLabel8.setText("Seconds");

        addActivityConfirmButton.setText("Confirm");
        addActivityConfirmButton.addActionListener(this::addActivityConfirmButtonActionPerformed);

        addActivityCancelButton.setText("Cancel");
        addActivityCancelButton.addActionListener(this::addActivityCancelButtonActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Add an activity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(addActivityTitleInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(panelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(addActivityTypeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(addActivityHoursInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(addActivityMinutesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(addActivitySecondsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addActivityConfirmButton)
                                        .addGap(100, 100, 100)
                                        .addComponent(addActivityCancelButton)
                                        .addGap(121, 121, 121))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel9)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addActivityTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addActivityTypeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(panelDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(addActivityHoursInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addActivityMinutesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addActivitySecondsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(addActivityConfirmButton)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addActivityCancelButton)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActivityTitleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActivityTitleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActivityTitleInputActionPerformed

    private void addActivityConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActivityConfirmButtonActionPerformed
        String title = addActivityTitleInput.getText();
        String description = addActivityDescriptionInput.getText();
        ActivityType type = (ActivityType) addActivityTypeSelect.getSelectedItem();
        LocalDateTime datetime = dateTimePicker.getDateTimePermissive();
        int hours = (int) addActivityHoursInput.getValue();
        int minutes = (int) addActivityMinutesInput.getValue();
        int seconds = (int) addActivitySecondsInput.getValue();
        int duration = hours * 3600 + minutes * 60 + seconds;
        
        Activity activity = new Activity(title, description, type, datetime, duration);
        ActivityService as = new ActivityService();
        
        try{
            as.add(activity);
        } catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error while adding new Activity!",
                "Database Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
        this.dispose();
        
        
    }//GEN-LAST:event_addActivityConfirmButtonActionPerformed

    private void addActivityCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActivityCancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_addActivityCancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddActivityDialog dialog = new AddActivityDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addActivityCancelButton;
    private javax.swing.JButton addActivityConfirmButton;
    private javax.swing.JTextArea addActivityDescriptionInput;
    private javax.swing.JSpinner addActivityHoursInput;
    private javax.swing.JSpinner addActivityMinutesInput;
    private javax.swing.JSpinner addActivitySecondsInput;
    private javax.swing.JTextField addActivityTitleInput;
    private javax.swing.JComboBox<ActivityType> addActivityTypeSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDateTime;
    // End of variables declaration//GEN-END:variables
}
