package com.mycompany.projetjava;
import com.mycompany.projetjava.models.User;
import com.mycompany.projetjava.services.UserService;
import javax.swing.JOptionPane;
/**
 *
 * @author miste
 */
public class AuthPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthPage.class.getName());

    /**
     * Creates new form AuthPage
     */
    public AuthPage() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(152,251,152));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        champID = new javax.swing.JLabel();
        champMDP = new javax.swing.JLabel();
        IdInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        connectionButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        champID.setText("Identifiant");

        champMDP.setText("Mot De Passe");

        IdInput.setBackground(new java.awt.Color(0, 204, 0));
        IdInput.addActionListener(this::IdInputActionPerformed);

        passwordInput.setBackground(new java.awt.Color(0, 204, 0));
        passwordInput.addActionListener(this::passwordInputActionPerformed);

        connectionButton.setBackground(new java.awt.Color(0, 129, 0));
        connectionButton.setForeground(new java.awt.Color(255, 255, 255));
        connectionButton.setText("Connexion");
        connectionButton.addActionListener(this::connectionButtonActionPerformed);

        createAccountButton.setBackground(new java.awt.Color(0, 129, 0));
        createAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        createAccountButton.setText("Créer un Compte");
        createAccountButton.addActionListener(this::createAccountButtonActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONNEXION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(champMDP)
                    .addComponent(champID)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdInput)
                    .addComponent(passwordInput)
                    .addComponent(connectionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(champID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(champMDP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(connectionButton)
                .addGap(18, 18, 18)
                .addComponent(createAccountButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdInputActionPerformed
        // TODO add your handling code here:
        connectionButton.doClick();
    }//GEN-LAST:event_IdInputActionPerformed

    private void connectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionButtonActionPerformed
        String loginSaisi = IdInput.getText();
        String mdpSaisi = new String(passwordInput.getPassword());


        if (loginSaisi.isEmpty() || mdpSaisi.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs.", 
                "Attention", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserService userService = new UserService();
        try{
            
            User user = userService.getUser(loginSaisi, mdpSaisi);
            if(user != null){
                UserSession.getInstance().setUser(user);
                
                
                
                HomePage home = new HomePage();
                home.setVisible(true);
                this.dispose();
                
            } else{
                JOptionPane.showMessageDialog(this, 
                    "Identifiants incorrects.", 
                    "Erreur d'authentification", 
                    JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erreur de communication avec la base : " + e.getMessage(), 
                "Erreur SQL", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_connectionButtonActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
        connectionButton.doClick();
    }//GEN-LAST:event_passwordInputActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        CreateAccount fenetreInscription = new CreateAccount();
           
        // 2. On l'affiche à l'écran
        fenetreInscription.setVisible(true);
       
        
        // 3. (Optionnel) On ferme la fenêtre de connexion actuelle pour ne pas encombrer l'écran
        this.dispose();
    }//GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuthPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdInput;
    private javax.swing.JLabel champID;
    private javax.swing.JLabel champMDP;
    private javax.swing.JButton connectionButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordInput;
    // End of variables declaration//GEN-END:variables
}
