package com.mycompany.projetjava;
import com.mycompany.projetjava.services.UserService;
import javax.swing.JOptionPane;
/**
 *
 * @author miste
 */
public class AuthPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthPage.class.getName());

    /**
     * Creates new form AuthPage
     */
    public AuthPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        champID = new javax.swing.JLabel();
        champMDP = new javax.swing.JLabel();
        userLoginIDInput = new javax.swing.JTextField();
        userLoginPasswordInput = new javax.swing.JPasswordField();
        userConnectionButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        champID.setText("Identifiant");

        champMDP.setText("Mot De Passe");

        userLoginIDInput.addActionListener(this::userLoginIDInputActionPerformed);

        userLoginPasswordInput.addActionListener(this::userLoginPasswordInputActionPerformed);

        userConnectionButton.setText("Connexion");
        userConnectionButton.addActionListener(this::userConnectionButtonActionPerformed);

        createAccountButton.setText("Créer un Compte");
        createAccountButton.addActionListener(this::createAccountButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(champID)
                            .addComponent(champMDP))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userLoginIDInput, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(userLoginPasswordInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(userConnectionButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(createAccountButton)))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(champID)
                    .addComponent(userLoginIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(champMDP)
                    .addComponent(userLoginPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(userConnectionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAccountButton)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userLoginIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLoginIDInputActionPerformed

    private void userConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userConnectionButtonActionPerformed
        String loginSaisi = userLoginIDInput.getText();
        String mdpSaisi = new String(userLoginPasswordInput.getPassword());


        if (loginSaisi.isEmpty() || mdpSaisi.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs.", 
                "Attention", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        UserService userService = new UserService();
        try{
            
            boolean exist = userService.userExist(loginSaisi, mdpSaisi);
        
            if(exist){
                JOptionPane.showMessageDialog(this, 
                    "Connexion réussie !",
                    "Succès", 
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else{
                JOptionPane.showMessageDialog(this, 
                    "Identifiants incorrects.", 
                    "Erreur d'authentification", 
                    JOptionPane.ERROR_MESSAGE
                );
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erreur de communication avec la base : " + e.getMessage(), 
                "Erreur SQL", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_userConnectionButtonActionPerformed

    private void userLoginPasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginPasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLoginPasswordInputActionPerformed

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        CreateAccount fenetreInscription = new CreateAccount();
        
        // 2. On l'affiche à l'écran
        fenetreInscription.setVisible(true);
        
        // 3. (Optionnel) On ferme la fenêtre de connexion actuelle pour ne pas encombrer l'écran
        this.dispose();
    }//GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuthPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel champID;
    private javax.swing.JLabel champMDP;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton userConnectionButton;
    private javax.swing.JTextField userLoginIDInput;
    private javax.swing.JPasswordField userLoginPasswordInput;
    // End of variables declaration//GEN-END:variables
}
